### ISSUE TITLE
Python error on new image version

### ISSUE THREAD

**Issue by andre-carvalho** [terrabrasilis/deter-cmask-task#1]
```sh
Traceback (most recent call last):
  File "zonal-cloud.py", line 18, in <module>
    import geopandas as gpd
  File "/usr/local/lib/python3.8/dist-packages/geopandas/__init__.py", line 1, in <module>
    from geopandas._config import options  # noqa
  File "/usr/local/lib/python3.8/dist-packages/geopandas/_config.py", line 109, in <module>
    default_value=_default_use_pygeos(),
  File "/usr/local/lib/python3.8/dist-packages/geopandas/_config.py", line 95, in _default_use_pygeos
    import geopandas._compat as compat
  File "/usr/local/lib/python3.8/dist-packages/geopandas/_compat.py", line 8, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.8/dist-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/usr/local/lib/python3.8/dist-packages/pandas/compat/__init__.py", line 16, in <module>
    from pandas._typing import F
  File "/usr/local/lib/python3.8/dist-packages/pandas/_typing.py", line 139, in <module>
    np.random.BitGenerator,
AttributeError: module 'numpy.random' has no attribute 'BitGenerator'
```

**Comment by andre-carvalho** [comment]
Change the Dockerfile base image to ubuntu:22.04

**Comment by andre-carvalho** [comment]
## But this change doesn't work

```sh
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/usr/bin/python3"
  * The NumPy version is: "1.26.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: PyCapsule_Import could not import module "datetime"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/gdal_calc.py", line 5, in <module>
    from osgeo_utils.gdal_calc import *  # noqa
  File "/usr/lib/python3/dist-packages/osgeo_utils/gdal_calc.py", line 44, in <module>
    import numpy
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 135, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 4: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 4: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 4: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ImportError: PyCapsule_Import could not import module "datetime"
```
